controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
    api_routes:
        path: /api
        controller: App\Controller\ApiController::apiEndpoint
        methods: [POST]


